spring.application.name=gateway
server.port=8086

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30
eureka.client.registryFetchIntervalSeconds=5

spring.cloud.gateway.mvc.routes[0].id=product-service-route
spring.cloud.gateway.mvc.routes[0].uri=lb://product-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/product/**

spring.cloud.gateway.mvc.routes[1].id=user-service-route
spring.cloud.gateway.mvc.routes[1].uri=lb://user-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/user/**

allowed.origins=https://192.168.13.166:9998,http://localhost:8086

logging.level.org.springframework.cloud.gateway=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://192.168.13.169:9998/auth/realms/master
#spring.security.oauth2.resourceserver.jwt.jwt-set-uri=https://192.168.13.166:9998/auth/realms/master/protocol/openid-connect/certs