spring.application.name=user-service
server.port=8084
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registryFetchIntervalSeconds=5

eureka.client.service-url.default=http://localhost:8761/eureka/
eureka.client.service-url.datasource.url=jdbc:h2:mem:userdb;
eureka.client.service-url.datasource.username=root
eureka.client.service-url.datasource.password=password
eureka.client.service-url.datasource.driver-class-name=org.h2.Driver
eureka.client.service-url.h2.console.enabled=true
eureka.client.service-url.jpa.hibernate.ddl-auto=update
eureka.client.service-url.jpa.show-sql=true
eureka.client.service-url.jpa.database-platform=org.hibernate.dialect.H2Dialect

eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30